# Site settings
title: pedromclamas
description: A blog about myself and my projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pedro Lamas
user_description: Personal website
user_title: Software Developer
email: lamas.pedromiguel@gmail.com
twitter_username: pedromclamas
github_username:  lamaspedro


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
